import { Router } from "express";
import { authRoutes } from "./auth.routes";
import { budgetRoutes } from "./budget.routes";
import { clientRoutes } from "./client.routes";
import { employeeRoutes } from "./employee.routes";
import { healthRoutes } from "./health.routes";
import { logisticsRoutes } from "./logistics.routes";
import { productRoutes } from "./product.routes";
import { productionRoutes } from "./production.routes";
import { publicRoutes } from "./public.routes";
import { stockRoutes } from "./stock.routes";
import { teamRoutes } from "./team.routes";
import { userRoutes } from "./user.routes";
import { paperboardRoutes } from "../modules/paperboard/paperboard.routes";
import { orderRoutes } from "../modules/orders/order.routes";
import { shipmentRoutes } from "../modules/shipments/shipment.routes";
import { financialRoutes } from "../modules/financial/financial.routes";
import { clicheRoutes } from "../modules/cliches/cliche.routes";
import { payableRoutes } from "../modules/accounts-payable/payable.routes";
import { deliveryRouteRoutes } from "../modules/delivery-routes/delivery-route.routes";
import { wasteRoutes } from "../modules/waste/waste.routes";
import { purchaseOrderRoutes } from "../modules/purchase-orders/purchase-order.routes";
import { consignedStockRoutes } from "../modules/consigned-stock/consigned-stock.routes";
import { pricingRoutes } from "../modules/pricing/pricing.routes";
import { dashboardRoutes } from "../modules/dashboard/dashboard.routes";
import { fichaTecnicaRoutes } from "./ficha-tecnica.routes";

const apiRoutes = Router();

apiRoutes.use("/health", healthRoutes);
apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/clients", clientRoutes);
apiRoutes.use("/logistics", logisticsRoutes);
apiRoutes.use("/budgets", budgetRoutes);
apiRoutes.use("/products", productRoutes);
apiRoutes.use("/stock", stockRoutes);
apiRoutes.use("/productions", productionRoutes);
apiRoutes.use("/public", publicRoutes);
apiRoutes.use("/employees", employeeRoutes);
apiRoutes.use("/teams", teamRoutes);
apiRoutes.use("/users", userRoutes);
apiRoutes.use("/", paperboardRoutes);
apiRoutes.use("/orders", orderRoutes);
apiRoutes.use("/", shipmentRoutes);
apiRoutes.use("/financial", financialRoutes);
apiRoutes.use("/cliches", clicheRoutes);
apiRoutes.use("/accounts-payable", payableRoutes);
apiRoutes.use("/delivery-routes", deliveryRouteRoutes);
apiRoutes.use("/waste", wasteRoutes);
apiRoutes.use("/purchase-orders", purchaseOrderRoutes);
apiRoutes.use("/consigned-stock", consignedStockRoutes);
apiRoutes.use("/pricing", pricingRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
apiRoutes.use("/ficha-tecnica", fichaTecnicaRoutes);

export { apiRoutes };
